### ISSUE TITLE
miniredis don't support Scan cmd.

### ISSUE THREAD

**Issue by zhuzhipeng1** [alicebob/miniredis#147]
package main

import (
	"fmt"

	"github.com/alicebob/miniredis"
	"github.com/go-redis/redis"
)

func main() {
	s, err := miniredis.Run()
	if err != nil {
		panic(err)
	}
	defer s.Close()
	s.Set("test1", "test1")
	s.Set("test2", "test2")
	s.Set("test3", "test3")
	s.Set("test4", "test4")
	s.Set("test5", "test5")
	s.Set("test6", "test6")
	s.Set("test7", "test7")
	s.Set("test8", "test8")
	s.Set("test9", "test9")
	s.Set("test10", "test10")
	s.Set("test11", "test11")
	s.Set("test12", "test12")
	s.Set("dn12", "dn23")
	c := redis.NewClient(&redis.Options{
		Addr: s.Addr(),
	})
	var value []string
	var num int64 = 2
	var cu uint64 = 0
	ret, cursor, err := c.Scan(cu, "test*", num).Result()
	fmt.Println(cursor)
	fmt.Println(ret)
	for cursor != 0 {
		value, cursor, err = c.Scan(cursor, "test*", num).Result()

		if err == nil {
			ret = append(ret, value...)
			value = value[:0]
		}
	}
	if len(value) != 0 {
		ret = append(ret, value...)
	}

}

When I use go-redis/redis Scan ,set count don't use.Scan return all match keys and cursor is 0.
[test1 test10 test11 test12 test2 test3 test4 test5 test6 test7 test8 test9]

**Comment by alicebob** [comment]
Miniredis does indeed not implement all the details of `SCAN`, but returns everything right away.

The documentation say:
> While SCAN does not provide guarantees about the number of elements returned at every iteration, it is possible to empirically adjust the behavior of SCAN using the COUNT option. Basically with COUNT the user specified the amount of work that should be done at every call in order to retrieve elements from the collection. This is just a hint for the implementation, however generally speaking this is what you could expect most of the times from the implementation.

https://redis.io/commands/scan
So I think this it's a fair enough implementation, especially since I expect people to use a client handling the details, so there is no difference then.

I would be open for a PR implementing proper cursors with all guarantees as documented by the link above. But I expect that it's not that easy.
