### ISSUE TITLE
v2.5.0 tag is gone

### ISSUE THREAD

**Issue by sureifyshain** [alicebob/miniredis#181]
Hi @alicebob -- I have encountered an error in a go library which requires v2.5.0 of this package. I am guessing that the tag was removed recently. Can we verify and/or re-add this tag?

**Comment by akimmgd** [comment]
+1 on this issue, we're encountering the same thing.

**Comment by dz2311** [comment]
+1, can you add 2.5.0 back? Thanks a lot!

**Comment by joshdegraw** [comment]
This also broke some of the deployments I'm using :+1:

**Comment by Cawb07** [comment]
It was removed within 7 days

**Comment by halucinka** [comment]
+1 on the issue. It was very sad to find this out.

**Comment by teodorlu** [comment]
Can we identify the SHA of `v2.5.0`, so that we can use the SHA instead of the tag?

**Comment by teodorlu** [comment]
SHA of `v2.5.0` seems to be b96c8f84fb2f6354ff335b49cab09327b8ca68ac

**Comment by alicebob** [comment]
Hi, sorry, I'll put it back right away.

**Comment by alicebob** [comment]
Ok, it's back (so are v2.4.5 and v2.4.6). I was trying to cleanup the +incompatible versions, because there are some v2 releases with go.mod, and some without go.mod. For example https://pkg.go.dev/github.com/alicebob/miniredis@v2.5.0+incompatible
Guess I can't do that. Sorry for the inconvenience!

(and btw, if possible, import the /v2 tag, it's completely compatible, and it's maintained. I should have created a v3 when adding to go.mod file back then)

**Comment by bhuvanvenkat-plivo** [comment]
@alicebob `go list -m all` with miniredis imported as `github.com/alicebob/miniredis/v2` is somehow listing v2.5.0+incompatible. This is causing `go mod vendor` also to fail.

my go.mod
`github.com/alicebob/miniredis/v2 v2.14.1`

import within the code
`"github.com/alicebob/miniredis/v2"`

**Comment by alicebob** [comment]
@bhuvanvenkat-plivo : that was already the case, or is that new?

I just made a new project, with this import: `import "github.com/alicebob/miniredis/v2"`. Go downloads and vendors the correct version (v2.14.1). That's with Go 1.15, at least.

**Comment by bhuvanvenkat-plivo** [comment]
@alicebob : Let me quickly retry on a new machine and see if my cached ones are causing any issue. Btw, thanks for the quick turn around.
